Fix bad grep which was stopping CI from working

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -68,9 +68,17 @@ jobs:
           sed -i 's/ctx/_context/' programs/project/src/lib.rs
           cargo add solana-program@"=1.18.5"
 
+          npm i
+          echo "----------------------------------------"
+          echo "Running 'anchor test'..."
           anchor test 2>&1 | tee -a build.log
+          echo "----------------------------------------"
+          echo "build.log..."
           cat build.log
-          cat build.log | grep -qEv 'error|warn'
+          echo "----------------------------------------"
+          echo "Checking for errors or warnings in build.log..."
+          grep -qiEvz 'error|warn|failed' build.log
+          echo $?
 
       - name: Test the Favorites project builds and tests pass
         run: |
@@ -84,5 +92,5 @@ jobs:
           cat build.log
           echo "----------------------------------------"
           echo "Checking for errors or warnings in build.log..."
-          grep -qiEv 'error|warn' build.log
+          grep -qiEvz 'error|warn|failed' build.log
           echo $?
