Debug checking for errors in build log

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -77,4 +77,7 @@ jobs:
           cd labs/favorites
           anchor test 2>&1 | tee -a build.log
           cat build.log
+          echo "----------------------------------------"
+          echo "Checking for errors or warnings in build.log..."
           grep -qiEv 'error|warn' build.log
+          echo $?
